### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by drtzack** [themsaid/laravel-mail-preview#10]
in /home/vagrant/mt2magic-com/vendor/laravel/framework/src/Illuminate/Http/Request.php line 859
at Request->session() in /home/vagrant/mt2magic-com/vendor/themsaid/laravel-mail-preview/src/MailPreviewMiddleware.php line 27
at MailPreviewMiddleware->handle(object(Request), object(Closure))

I keep getting "Session store not set on request"

**Comment by themsaid** [comment]
I've published a new patch v1.2.1, please check and let me know if the issue was fixed.

**Comment by drtzack** [comment]
It is fixed. Thank you :)

**Comment by themsaid** [comment]
💯

**Comment by mikemand** [comment]
This didn't solve the problem for me. Could it be related to this change: https://github.com/laravel/laravel/commit/5c30c98db96459b4cc878d085490e4677b0b67ed?

**Comment by themsaid** [comment]
@mikemand what's the error you get?

**Comment by mikemand** [comment]
Hi @themsaid,

I get the same error as @drtzack:

![laravel-mail-preview session error](https://cloud.githubusercontent.com/assets/745184/14830449/5d4fa586-0bb6-11e6-888f-58d4f8e4bd7c.png)

**Comment by quincy-soeliman** [comment]
Like @mikemand said, turning off the show_link_to_preview option to false works.

**Comment by Luddinus** [comment]
Same issue here, instead of returning error 404, if I have "show_link_to_preview" true, it gives this error.
